#!/usr/bin/ruby
require_relative '../requires.rb'

config_settings = {
  :nick         => 'x509',
  :owner        => 'Ninjex',
  :server       => 'irc.hackthissite.org',
  :port         => '7000',
  :ssl          => true,
  :chans        => '#bots',
  :command_list => [],
}

@bot = Bot.new(config_settings)
@bot.info
@bot.start
